In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import numpy as np
import statsmodels.api as sm
from statistics import t_test, t_test_binary_col, anova

In [5]:
font_path = "C:/Windows/Fonts/msjh.ttc"
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei']  # 微軟正黑體
plt.rcParams['axes.unicode_minus'] = False  # 正負號也要支援中文

# EDA

In [6]:
data = pd.read_csv('LDA topics.csv')
 # 薪資正規化
data['max_salary_K'] = data['max_salary'] / 1000
data['min_salary_K'] = data['min_salary'] / 1000

In [7]:
salary_data = data[(data['max_salary'] > 0)&(data['max_salary'] < 500000)&(data['salaryType'] != 'H')&(data['salaryType'] != 'D')].copy()
analyst_data = salary_data[(salary_data['topic_job_category']=='BA')|((salary_data['topic_job_category']=='DA')|((salary_data['topic_job_category']=='DS')))].copy()

## 1. 產業 v.s. 薪資

In [8]:
industries = list(salary_data['coIndustryDesc'].unique())
t_test(salary_data, 'coIndustryDesc', industries, 'max_salary_K', 0.1)

,coIndustryDesc,mean max_salary_K_with,mean max_salary_K_not_with,mean_diff,p_value
6,工商顧問服務業,55.547619,81.121349,-25.573730,3.084588e-08
3,電腦軟體服務業,99.520868,74.757592,24.763276,1.099829e-04
4,醫院,59.006923,80.378608,-21.371685,3.273061e-04

In [9]:
salary_data['industry_group_no'] = salary_data['coIndustry'].astype(str).str[:7]
industries_no = list(salary_data['industry_group_no'].unique())
test_df = t_test(salary_data, 'industry_group_no', industries_no, 'max_salary_K', 0.05)

In [10]:
industry_map = {
    '1001001': '電腦軟體相關產業',
    '1001003': '電腦設備相關產業',
    '1012001': '醫療業',
    '1008003': '工商顧問及其他專業'
}

test_df['industry_group'] = test_df['industry_group_no'].apply(lambda x: industry_map[x])
test_df

,industry_group_no,mean max_salary_K_with,mean max_salary_K_not_with,mean_diff,p_value,industry_group
2,1001003,60.545455,80.202078,-19.656623,1.370384e-08,電腦設備相關產業
0,1001001,90.047270,70.305676,19.741595,5.396879e-05,電腦軟體相關產業
4,1012001,59.077857,80.439440,-21.361583,1.294801e-04,醫療業
5,1008003,61.779677,81.318026,-19.538349,4.088871e-04,工商顧問及其他專業

In [11]:
test_df = t_test(salary_data, 'industry_group_no', industries_no, 'min_salary_K', 0.05)

In [12]:
test_df['industry_group'] = test_df['industry_group_no'].apply(lambda x: industry_map[x])
test_df

,industry_group_no,mean min_salary_K_with,mean min_salary_K_not_with,mean_diff,p_value,industry_group
2,1001003,32.818182,50.300108,-17.481927,2.179097e-24,電腦設備相關產業
0,1001001,56.162343,44.063850,12.098493,9.401251e-07,電腦軟體相關產業
4,1012001,40.980357,50.115557,-9.135200,1.004689e-04,醫療業

## 2. 學歷 v.s 薪資

In [13]:
edu = list(salary_data['optionEdu'].unique())
print(edu)
test_df = t_test(salary_data, 'optionEdu', edu, 'max_salary_K', 0.05)
test_df

['大學', '學歷不拘', '碩士', '專科', '高中', '高中以下', '博士']

,optionEdu,mean max_salary_K_with,mean max_salary_K_not_with,mean_diff,p_value
3,專科,65.339461,83.029249,-17.689788,0.000148

In [14]:
edu = list(salary_data['optionEdu'].unique())
test_df = t_test(salary_data, 'optionEdu', edu, 'min_salary_K', 0.05)
test_df

,optionEdu,mean min_salary_K_with,mean min_salary_K_not_with,mean_diff,p_value
3,專科,43.191520,51.335991,-8.144471,0.000309
0,大學,52.239699,46.521158,5.718541,0.014011

## 3. 學系要求 v.s. 薪資

In [15]:
majors = ['major_資訊工程相關', 'major_資訊管理相關',
       'major_電機電子工程相關', 'major_數學及電算機科學學科類', 'major_數理統計相關',
       'major_其他數學及電算機科學相關', 'major_統計學相關', 'major_商業及管理學科類', 'major_工程學科類',
       'major_應用數學相關', 'major_財稅金融相關', 'major_工業工程相關', 'major_一般商業學類',
       'major_會計學相關', 'major_機械工程相關']
test_df = t_test_binary_col(salary_data, majors, 'min_salary_K', 0.05)
test_df

,name,mean min_salary_K_with,mean min_salary_K_not_with,mean_diff,p_value
6,major_統計學相關,38.130208,50.921987,-12.791779,1.063955e-08
4,major_數理統計相關,39.937037,50.571853,-10.634816,9.964822e-08
1,major_資訊管理相關,40.609087,51.685008,-11.075921,6.602039e-07

In [16]:
test_df = t_test_binary_col(salary_data, majors, 'max_salary_K', 0.05)
test_df

,name,mean max_salary_K_with,mean max_salary_K_not_with,mean_diff,p_value
6,major_統計學相關,57.572917,81.804319,-24.231402,5.107862e-09
4,major_數理統計相關,60.977778,81.142554,-20.164776,1.641066e-07
1,major_資訊管理相關,65.188842,82.631191,-17.442349,2.076348e-05
2,major_電機電子工程相關,103.185417,76.527138,26.658279,2.602563e-02
5,major_其他數學及電算機科學相關,106.786576,77.752286,29.034289,3.881663e-02

In [17]:
salary_data['major_group_infomation'] =  salary_data[['major_資訊工程相關', 'major_資訊工程相關']].sum(axis=1).gt(0).astype(int)
salary_data['major_group_engineer'] = salary_data[['major_電機電子工程相關', 'major_工程學科類', 'major_機械工程相關']].sum(axis=1).gt(0).astype(int)
salary_data['major_group_math_and_stats'] =  salary_data[['major_數學及電算機科學學科類', 'major_數理統計相關', 'major_其他數學及電算機科學相關', 'major_應用數學相關', 'major_統計學相關']].sum(axis=1).gt(0).astype(int)
salary_data['major_group_commercial'] = salary_data[['major_商業及管理學科類', 'major_一般商業學類']].sum(axis=1).gt(0).astype(int)

major_group = ['major_group_infomation', 'major_group_engineer', 'major_group_math_and_stats', 'major_group_commercial']
test_df = t_test_binary_col(salary_data, major_group, 'max_salary_K', 0.1)
test_df

,name,mean max_salary_K_with,mean max_salary_K_not_with,mean_diff,p_value
3,major_group_commercial,58.070000,80.217116,-22.147116,0.003614
1,major_group_engineer,99.988562,76.090220,23.898342,0.014460

In [18]:
salary_data['major_group_infomation'] =  salary_data[['major_資訊工程相關', 'major_資訊工程相關']].sum(axis=1).gt(0).astype(int)
salary_data['major_group_engineer'] = salary_data[['major_電機電子工程相關', 'major_工程學科類', 'major_機械工程相關']].sum(axis=1).gt(0).astype(int)
salary_data['major_group_math_and_stats'] =  salary_data[['major_數學及電算機科學學科類', 'major_數理統計相關', 'major_其他數學及電算機科學相關', 'major_應用數學相關', 'major_統計學相關']].sum(axis=1).gt(0).astype(int)
salary_data['major_group_commercial'] = salary_data[['major_商業及管理學科類', 'major_一般商業學類']].sum(axis=1).gt(0).astype(int)

major_group = ['major_group_infomation', 'major_group_engineer', 'major_group_math_and_stats', 'major_group_commercial']
test_df = t_test_binary_col(salary_data, major_group, 'min_salary_K', 0.1)
test_df

,name,mean min_salary_K_with,mean min_salary_K_not_with,mean_diff,p_value
1,major_group_engineer,55.94183,48.689273,7.252557,0.073213

## 4. 年資 v.s. 薪資

In [19]:
periods = list(data['periodDesc'].unique())
test_df = t_test(salary_data, 'periodDesc', periods, 'min_salary_K', 0.1)
test_df

,periodDesc,mean min_salary_K_with,mean min_salary_K_not_with,mean_diff,p_value
0,經歷不拘,43.417291,55.559060,-12.141769,2.801092e-07
2,1年以上,41.304053,51.397622,-10.093570,7.485589e-07
4,5年以上,89.969841,47.173994,42.795847,1.339979e-04
3,3年以上,61.311007,48.037636,13.273371,1.284618e-03

In [20]:
test_df = t_test(salary_data, 'periodDesc', periods, 'max_salary_K', 0.1)
test_df

,periodDesc,mean max_salary_K_with,mean max_salary_K_not_with,mean_diff,p_value
0,經歷不拘,67.237425,90.910178,-23.672753,6.390698e-07
4,5年以上,136.227778,75.955851,60.271927,1.059477e-03
3,3年以上,98.229956,76.822218,21.407737,4.392837e-03

## 5. 縣市 v.s. 薪資

In [21]:
salary_data['region'] = salary_data['jobAddrNoDesc'].str[:3]
regions=list(salary_data['region'].str[:3].unique())

anova(salary_data, 'region', 'min_salary_K')

F統計量: 3.17
p-value: 0.0002
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
group1 group2 meandiff p-adj    lower    upper   reject
-------------------------------------------------------
   台中市    台北市  13.4162 0.0267    0.7406  26.0918   True
   台中市    台南市   0.3984    1.0  -25.7216  26.5184  False
   台中市    嘉義市   3.2984    1.0  -50.4274  57.0243  False
   台中市    宜蘭縣  -7.3016    1.0   -82.413  67.8099  False
   台中市    彰化縣  -7.2349    1.0  -51.5976  37.1277  False
   台中市    新北市  -1.8571    1.0  -19.1253   15.411  False
   台中市    新竹市   -0.647    1.0  -25.7898  24.4957  False
   台中市    新竹縣  15.3567 0.6763   -8.9417  39.6552  False
   台中市     日本  12.6984    1.0   -62.413  87.8099  False
   台中市    桃園市   2.6762    1.0  -18.2366  23.5889  False
   台中市    美國加  41.0317 0.8535  -34.0797 116.1432  False
   台中市    花蓮縣  -2.3016    1.0   -77.413  72.8099  False
   台中市    高雄市  -3.9516    1.0  -22.2627  14.3595  False
   台北市    台南市 -13.0178 0.8632  -37.1118  11.0762  False
   台北市    嘉義市 -10.1178    1.0  -62.8883  42.6528  False
   台北市    宜蘭縣 -20.7178 0.9996  -95.1489  53.7134  False
   台北市    彰化縣 -20.6511 0.9412  -63.8519  22.5497  False
   台北市    新北市 -15.2733 0.0187  -29.2895  -1.2571   True
   台北市    新竹市 -14.0632  0.726  -37.0942   8.9677  False
   台北市    新竹縣   1.9406    1.0  -20.1655  24.0467  False
   台北市     日本  -0.7178    1.0  -75.1489  73.7134  False
   台北市    桃園市   -10.74 0.7787  -29.0596   7.5796  False
   台北市    美國加  27.6156 0.9932  -46.8156 102.0467  False
   台北市    花蓮縣 -15.7178    1.0  -90.1489  58.7134  False
   台北市    高雄市 -17.3678 0.0107  -32.6505   -2.085   True
   台南市    嘉義市      2.9    1.0  -54.6006  60.4006  False
   台南市    宜蘭縣     -7.7    1.0  -85.5561  70.1561  False
   台南市    彰化縣  -7.6333    1.0  -56.4994  41.2328  False
   台南市    新北市  -2.2556    1.0  -29.0518  24.5407  False
   台南市    新竹市  -1.0455    1.0  -33.4802  31.3892  False
   台南市    新竹縣  14.9583 0.9478  -16.8263   46.743  False
   台南市     日本     12.3    1.0  -65.5561  90.1561  False
   台南市    桃園市   2.2778    1.0  -27.0001  31.5556  False
   台南市    美國加  40.6333 0.8907  -37.2228 118.4895  False
   台南市    花蓮縣     -2.7    1.0  -80.5561  75.1561  False
   台南市    高雄市    -4.35    1.0  -31.8299  23.1299  False
   嘉義市    宜蘭縣    -10.6    1.0 -101.5164  80.3164  False
   嘉義市    彰化縣 -10.5333    1.0  -78.2984  57.2317  False
   嘉義市    新北市  -5.1556    1.0  -59.2134  48.9023  False
   嘉義市    新竹市  -3.9455    1.0  -61.0088  53.1178  False
   嘉義市    新竹縣  12.0583    1.0   -44.638  68.7547  False
   嘉義市     日本      9.4    1.0  -81.5164 100.3164  False
   嘉義市    桃園市  -0.6222    1.0  -55.9522  54.7077  False
   嘉義市    美國加  37.7333 0.9812  -53.1831 128.6497  False
   嘉義市    花蓮縣     -5.6    1.0  -96.5164  85.3164  False
   嘉義市    高雄市    -7.25    1.0    -61.65    47.15  False
   宜蘭縣    彰化縣   0.0667    1.0  -85.6501  85.7835  False
   宜蘭縣    新北市   5.4444    1.0  -69.9048  80.7937  False
   宜蘭縣    新竹市   6.6545    1.0  -70.8792  84.1883  False
   宜蘭縣    新竹縣  22.6583 0.9994  -54.6057  99.9224  False
   宜蘭縣     日本     20.0    1.0  -84.9812 124.9812  False
   宜蘭縣    桃園市   9.9778    1.0  -66.2893  86.2449  False
   宜蘭縣    美國加  48.3333 0.9559  -56.6479 153.3145  False
   宜蘭縣    花蓮縣      5.0    1.0  -99.9812 109.9812  False
   宜蘭縣    高雄市     3.35    1.0  -72.2451  78.9451  False
   彰化縣    新北市   5.3778    1.0  -39.3864  50.1419  False
   彰化縣    新竹市   6.5879    1.0  -41.7629  54.9387  False
   彰化縣    新竹縣  22.5917  0.947  -25.3255  70.5088  False
   彰化縣     日本  19.9333    1.0  -65.7835 105.6501  False
   彰化縣    桃園市   9.9111    1.0  -36.3812  56.2035  False
   彰化縣    美國加  48.2667  0.824  -37.4501 133.9835  False
   彰化縣    花蓮縣   4.9333    1.0  -80.7835  90.6501  False
   彰化縣    高雄市   3.2833    1.0  -41.8934    48.46  False
   新北市    新竹市   1.2101    1.0  -24.6345  27.0547  False
   新北市    新竹縣  17.2139 0.5383     -7.81  42.2378  False
   新北市     日本  14.5556    1.0  -60.7937  89.9048  False
   新北市    桃園市   4.5333    1.0  -17.2181  26.2848  False
   新北市    美國加  42.8889 0.8125  -32.4604 118.2382  False
   新北市    花蓮縣  -0.4444    1.0  -75.7937  74.9048  False
   新北市    高雄市  -2.0944    1.0  -21.3579   17.169  False
   新竹市    新竹縣  16.0038 0.8981  -14.9828  46.9904  False
   新竹市     日本  13.3455    1.0  -64.1883  90.8792  False
   新竹市    桃園市   3.3232    1.0  -25.0862  31.7327  False
   新竹市    美國加  41.6788 0.8675   -35.855 119.2125  False
   新竹市    花蓮縣  -1.6545    1.0  -79.1883  75.8792  False
   新竹市    高雄市  -3.3045    1.0  -29.8573  23.2482  False
   新竹縣     日本  -2.6583    1.0  -79.9224  74.6057  False
   新竹縣    桃園市 -12.6806 0.9574  -40.3455  14.9844  False
   新竹縣    美國加   25.675 0.9977  -51.5891 102.9391  False
   新竹縣    花蓮縣 -17.6583    1.0  -94.9224  59.6057  False
   新竹縣    高雄市 -19.3083 0.3886   -45.063   6.4464  False
    日本    桃園市 -10.0222    1.0  -86.2893  66.2449  False
    日本    美國加  28.3333 0.9997  -76.6479 133.3145  False
    日本    花蓮縣    -15.0    1.0 -119.9812  89.9812  False
    日本    高雄市   -16.65    1.0  -92.2451  58.9451  False
   桃園市    美國加  38.3556 0.9152  -37.9115 114.6226  False
   桃園市    花蓮縣  -4.9778    1.0  -81.2449  71.2893  False
   桃園市    高雄市  -6.6278 0.9994  -29.2161  15.9606  False
   美國加    花蓮縣 -43.3333 0.9821 -148.3145  61.6479  False
   美國加    高雄市 -44.9833 0.7602 -120.5784  30.6118  False
   花蓮縣    高雄市    -1.65    1.0  -77.2451  73.9451  False
-------------------------------------------------------

In [22]:
salary_data['region'] = salary_data['jobAddrNoDesc'].str[:3]
regions=list(salary_data['region'].str[:3].unique())

anova(salary_data, 'region', 'max_salary_K')

F統計量: 3.40
p-value: 0.0001
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
group1 group2 meandiff p-adj    lower    upper   reject
-------------------------------------------------------
   台中市    台北市  21.6549 0.1851   -3.6187  46.9284  False
   台中市    台南市  -4.7786    1.0  -56.8586  47.3015  False
   台中市    嘉義市  -5.5786    1.0 -112.7011  101.544  False
   台中市    宜蘭縣  -6.1786    1.0 -155.9413 143.5842  False
   台中市    彰化縣  -0.7786    1.0  -89.2321   87.675  False
   台中市    新北市  -1.7947    1.0  -36.2252  32.6358  False
   台中市    新竹市   3.5487    1.0  -46.5828  53.6803  False
   台中市    新竹縣  67.1881 0.0003   18.7401 115.6361   True
   台中市     日本  18.8214    1.0 -130.9413 168.5842  False
   台中市    桃園市   1.0733    1.0  -40.6241  42.7707  False
   台中市    美國加  58.8214 0.9885  -90.9413 208.5842  False
   台中市    花蓮縣  -0.1786    1.0 -149.9413 149.5842  False
   台中市    高雄市  -6.9212    1.0  -43.4312  29.5889  False
   台北市    台南市 -26.4334 0.8468  -74.4738   21.607  False
   台北市    嘉義市 -27.2334 0.9998 -132.4513  77.9844  False
   台北市    宜蘭縣 -27.8334    1.0 -176.2397 120.5729  False
   台北市    彰化縣 -22.4334 0.9998 -108.5704  63.7035  False
   台北市    新北市 -23.4496 0.2125  -51.3961   4.4969  False
   台北市    新竹市 -18.1062  0.988   -64.027  27.8147  False
   台北市    新竹縣  45.5332 0.0353    1.4565    89.61   True
   台北市     日本  -2.8334    1.0 -151.2397 145.5729  False
   台北市    桃園市 -20.5816 0.8233  -57.1086  15.9454  False
   台北市    美國加  37.1666 0.9999 -111.2397 185.5729  False
   台北市    花蓮縣 -21.8334    1.0 -170.2397 126.5729  False
   台北市    高雄市  -28.576 0.0921  -59.0478   1.8958  False
   台南市    嘉義市     -0.8    1.0 -115.4489 113.8489  False
   台南市    宜蘭縣     -1.4    1.0 -156.6353 153.8353  False
   台南市    彰化縣      4.0    1.0  -93.4328 101.4328  False
   台南市    新北市   2.9838    1.0  -50.4445  56.4121  False
   台南市    新竹市   8.3273    1.0  -56.3434   72.998  False
   台南市    新竹縣  71.9667 0.0108    8.5921 135.3412   True
   台南市     日本     23.6    1.0 -131.6353 178.8353  False
   台南市    桃園市   5.8519    1.0  -52.5245  64.2282  False
   台南市    美國加     63.6 0.9832  -91.6353 218.8353  False
   台南市    花蓮縣      4.6    1.0 -150.6353 159.8353  False
   台南市    高雄市  -2.1426    1.0  -56.9341  52.6489  False
   嘉義市    宜蘭縣     -0.6    1.0 -181.8758 180.6758  False
   嘉義市    彰化縣      4.8    1.0  -130.315  139.915  False
   嘉義市    新北市   3.7838    1.0 -104.0006 111.5683  False
   嘉義市    新竹市   9.1273    1.0 -104.6497 122.9043  False
   嘉義市    新竹縣  72.7667 0.6481  -40.2787  185.812  False
   嘉義市     日本     24.4    1.0 -156.8758 205.6758  False
   嘉義市    桃園市   6.6519    1.0 -103.6691 116.9728  False
   嘉義市    美國加     64.4 0.9955 -116.8758 245.6758  False
   嘉義市    花蓮縣      5.4    1.0 -175.8758 186.6758  False
   嘉義市    高雄市  -1.3426    1.0 -109.8093 107.1241  False
   宜蘭縣    彰化縣      5.4    1.0 -165.5085 176.3085  False
   宜蘭縣    新北市   4.3838    1.0 -145.8531 154.6208  False
   宜蘭縣    新竹市   9.7273    1.0 -144.8652 164.3198  False
   宜蘭縣    新竹縣  73.3667 0.9429  -80.6881 227.4215  False
   宜蘭縣     日本     25.0    1.0 -184.3193 234.3193  False
   宜蘭縣    桃園市   7.2519    1.0 -144.8151 159.3188  False
   宜蘭縣    美國加     65.0 0.9988 -144.3193 274.3193  False
   宜蘭縣    花蓮縣      6.0    1.0 -203.3193 215.3193  False
   宜蘭縣    高雄市  -0.7426    1.0 -151.4697 149.9845  False
   彰化縣    新北市  -1.0162    1.0  -90.2702  88.2379  False
   彰化縣    新竹市   4.3273    1.0  -92.0781 100.7326  False
   彰化縣    新竹縣  67.9667 0.4799  -27.5741 163.5074  False
   彰化縣     日本     19.6    1.0 -151.3085 190.5085  False
   彰化縣    桃園市   1.8519    1.0  -90.4493   94.153  False
   彰化縣    美國加     59.6 0.9962 -111.3085 230.5085  False
   彰化縣    花蓮縣      0.6    1.0 -170.3085 171.5085  False
   彰化縣    高雄市  -6.1426    1.0  -96.2193  83.9341  False
   新北市    新竹市   5.3434    1.0  -46.1874  56.8743  False
   新北市    新竹縣  68.9828 0.0004   19.0883 118.8773   True
   新北市     日本  20.6162    1.0 -129.6208 170.8531  False
   新北市    桃園市    2.868    1.0  -40.5017  46.2377  False
   新北市    美國加  60.6162 0.9853  -89.6208 210.8531  False
   新北市    花蓮縣   1.6162    1.0 -148.6208 151.8531  False
   新北市    高雄市  -5.1264    1.0  -43.5353  33.2824  False
   新竹市    新竹縣  63.6394 0.0364    1.8561 125.4227   True
   新竹市     日本  15.2727    1.0 -139.3198 169.8652  False
   新竹市    桃園市  -2.4754    1.0  -59.1203  54.1695  False
   新竹市    美國加  55.2727 0.9952  -99.3198 209.8652  False
   新竹市    花蓮縣  -3.7273    1.0 -158.3198 150.8652  False
   新竹市    高雄市 -10.4699    1.0  -63.4128   42.473  False
   新竹縣     日本 -48.3667 0.9987 -202.4215 105.6881  False
   新竹縣    桃園市 -66.1148 0.0049 -121.2753 -10.9543   True
   新竹縣    美國加  -8.3667    1.0 -162.4215 145.6881  False
   新竹縣    花蓮縣 -67.3667 0.9708 -221.4215  86.6881  False
   新竹縣    高雄市 -74.1093 0.0001 -125.4609 -22.7577   True
    日本    桃園市 -17.7481    1.0 -169.8151 134.3188  False
    日本    美國加     40.0    1.0 -169.3193 249.3193  False
    日本    花蓮縣    -19.0    1.0 -228.3193 190.3193  False
    日本    高雄市 -25.7426    1.0 -176.4697 124.9845  False
   桃園市    美國加  57.7481 0.9915  -94.3188 209.8151  False
   桃園市    花蓮縣  -1.2519    1.0 -153.3188 150.8151  False
   桃園市    高雄市  -7.9944    1.0  -53.0328  37.0439  False
   美國加    花蓮縣    -59.0 0.9996 -268.3193 150.3193  False
   美國加    高雄市 -65.7426 0.9714 -216.4697  84.9845  False
   花蓮縣    高雄市  -6.7426    1.0 -157.4697 143.9845  False
-------------------------------------------------------

In [23]:
region_map = {
    # 北部
    '台北市': '北部',
    '新北市': '北部',
    '基隆市': '北部',
    '桃園市': '北部',
    '新竹市': '北部',
    '新竹縣': '北部',

    # 中部
    '台中市': '中部',
    '苗栗縣': '中部',
    '彰化縣': '中部',
    '南投縣': '中部',
    '雲林縣': '中部',

    # 南部
    '台南市': '南部',
    '高雄市': '南部',
    '嘉義市': '南部',
    '嘉義縣': '南部',
    '屏東縣': '南部',

    # 東部
    '宜蘭縣': '東部',
    '花蓮縣': '東部',
    '台東縣': '東部',

    # 離島 & 外國
    '澎湖縣': '外島',
    '金門縣': '外島',
    '連江縣': '外島'
}

In [24]:
salary_data['region_group'] = salary_data['region'].apply(lambda x: region_map[x] if x in region_map.keys() else '其他')
region_group=list(salary_data['region_group'].str[:3].unique())

anova(salary_data, 'region_group', 'min_salary_K')

F統計量: 4.88
p-value: 0.0008
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
    中部     其他  27.3474 0.4395 -16.9461 71.6409  False
    中部     北部  10.7232 0.0261   0.8298 20.6166   True
    中部     南部  -1.9821 0.9943 -15.3916 11.4274  False
    中部     東部  -4.3193 0.9989 -48.6128 39.9742  False
    其他     北部 -16.6242 0.8328 -60.1308 26.8824  False
    其他     南部 -29.3295 0.3695 -73.7677 15.1088  False
    其他     東部 -31.6667 0.6172 -92.9599 29.6265  False
    北部     南部 -12.7053  0.009 -23.2278 -2.1828   True
    北部     東部 -15.0425 0.8777 -58.5491 28.4641  False
    南部     東部  -2.3372 0.9999 -46.7754 42.1011  False
-----------------------------------------------------

In [25]:
anova(salary_data, 'region_group', 'max_salary_K')

F統計量: 3.98
p-value: 0.0036
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
=======================================================
group1 group2 meandiff p-adj    lower    upper   reject
-------------------------------------------------------
    中部     其他  38.8733 0.7536  -50.2399 127.9866  False
    中部     北部  18.6528 0.0783   -1.2515  38.5572  False
    中部     南部   -6.251 0.9692  -33.2294  20.7273  False
    中部     東部  -3.1267    1.0  -92.2399  85.9866  False
    其他     北部 -20.2205 0.9695 -107.7506  67.3096  False
    其他     南部 -45.1244 0.6383 -134.5288  44.2801  False
    其他     東部    -42.0 0.8835 -165.3146  81.3146  False
    北部     南部 -24.9039 0.0119   -46.074  -3.7338   True
    北部     東部 -21.7795 0.9602 -109.3096  65.7506  False
    南部     東部   3.1244    1.0  -86.2801  92.5288  False
-------------------------------------------------------

## 6. 遠端工作 v.s. 薪資

In [26]:
salary_data['is_remote'] = salary_data['remote_desc'].apply(lambda x: 1 if x=='遠端工作' else 0)
test_df = t_test(salary_data, 'is_remote', [0, 1] , 'min_salary_K', 0.1)
test_df

,is_remote,mean min_salary_K_with,mean min_salary_K_not_with,mean_diff,p_value
0,0,47.249786,63.707547,-16.457761,0.000302
1,1,63.707547,47.249786,16.457761,0.000302

In [27]:
salary_data['is_remote'] = salary_data['remote_desc'].apply(lambda x: 1 if x=='遠端工作' else 0)
test_df = t_test(salary_data, 'is_remote', [0, 1] , 'max_salary_K', 0.1)
test_df

,is_remote,mean max_salary_K_with,mean max_salary_K_not_with,mean_diff,p_value
0,0,74.943026,105.493711,-30.550685,0.000114
1,1,105.493711,74.943026,30.550685,0.000114

## 7. 公司規模 v.s. 薪資

In [60]:
def scale_company(num):

    if num <= 50:
        return '1. 50人以下'
#     if num <= 100:
#         return '2 51~100'
    if num <= 200:
        return '3. 50~200'
#     if num <= 500:
#         return '4. 201~500'
    return '5. >500'

In [61]:
salary_data[['employees']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 349 entries, 4 to 1946
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   employees  349 non-null    float64
dtypes: float64(1)
memory usage: 5.5 KB

In [62]:
salary_data['employees'] = salary_data['employees'].fillna(10)
salary_data['company_scale'] = salary_data['employees'].apply(lambda x: scale_company(x))

In [63]:
anova(salary_data, 'company_scale', 'min_salary_K')

F統計量: 13.86
p-value: 0.0000
    Multiple Comparison of Means - Tukey HSD, FWER=0.05
===========================================================
  group1    group2  meandiff p-adj   lower    upper  reject
-----------------------------------------------------------
 1. 50人以下 3. 50~200   -0.616 0.9747  -7.3445  6.1125  False
 1. 50人以下   5. >500 -14.1781    0.0 -20.9066 -7.4496   True
3. 50~200   5. >500 -13.5622 0.0001 -21.0908 -6.0335   True
-----------------------------------------------------------